### ISSUE TITLE
MediaPipe API changed？

### ISSUE THREAD

**Issue by xugaoxiang** [pythonlessons/background_removal#1]
Error raised when I run main.py script using mediapipe 0.8.3

`
Traceback (most recent call last):
  File ".\main.py", line 7, in <module>
    mpFaceDetector = MPFaceDetection()
  File "C:\Users\xgx\Downloads\Compressed\background_removal-main\faceDetection.py", line 31, in __init__
    self.face_detection = self.mp_face_detection.FaceDetection(model_selection=model_selection, min_detection_confidence=confidence)
TypeError: __init__() got an unexpected keyword argument 'model_selection'
`

Is it right change code from

`
self.face_detection = self.mp_face_detection.FaceDetection(model_selection=model_selection, min_detection_confidence=confidence)
`

to 

`
self.face_detection = self.mp_face_detection.FaceDetection(min_detection_confidence=confidence)
`

?

Thanks.

**Comment by pythonlessons** [comment]
Hi, I have not checked how it was implemented in 0.8.3, but why not update to a newer version?

But if you want to stay with 0.8.3 then yes, this is the right change

**Comment by xugaoxiang** [comment]
Thanks.
